version: "2"
services:
  app:
    build: app
    container_name: "Assigment3-1"
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: "MySQL_Database_biostats-1"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro